//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatApp_xamarin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatApp_xamarin.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add members.
        /// </summary>
        internal static string addMembers {
            get {
                return ResourceManager.GetString("addMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string alert {
            get {
                return ResourceManager.GetString("alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to sign out?.
        /// </summary>
        internal static string areyousurewanttosignout {
            get {
                return ResourceManager.GetString("areyousurewanttosignout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must atleast 6 characters.
        /// </summary>
        internal static string atleast6char {
            get {
                return ResourceManager.GetString("atleast6char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your email to verify account.
        /// </summary>
        internal static string checkyouremail {
            get {
                return ResourceManager.GetString("checkyouremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string confirmpass {
            get {
                return ResourceManager.GetString("confirmpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string conversationTitle {
            get {
                return ResourceManager.GetString("conversationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account successfully.
        /// </summary>
        internal static string createaccountsuccessfully {
            get {
                return ResourceManager.GetString("createaccountsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account.
        /// </summary>
        internal static string createnewacount {
            get {
                return ResourceManager.GetString("createnewacount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark mode.
        /// </summary>
        internal static string darkmode {
            get {
                return ResourceManager.GetString("darkmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        internal static string displayname {
            get {
                return ResourceManager.GetString("displayname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have any code?.
        /// </summary>
        internal static string donthaveanycode {
            get {
                return ResourceManager.GetString("donthaveanycode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email does not exist.
        /// </summary>
        internal static string emaildoesnotexist {
            get {
                return ResourceManager.GetString("emaildoesnotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email existed.
        /// </summary>
        internal static string emailexisted {
            get {
                return ResourceManager.GetString("emailexisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your verification code.
        /// </summary>
        internal static string enteryourverificationcode {
            get {
                return ResourceManager.GetString("enteryourverificationcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string forgotpass {
            get {
                return ResourceManager.GetString("forgotpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        internal static string friendsTitle {
            get {
                return ResourceManager.GetString("friendsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        internal static string groupname {
            get {
                return ResourceManager.GetString("groupname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        internal static string incorrectpassword {
            get {
                return ResourceManager.GetString("incorrectpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format.
        /// </summary>
        internal static string invalidemailformat {
            get {
                return ResourceManager.GetString("invalidemailformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member already existed.
        /// </summary>
        internal static string memberalreadyexisted {
            get {
                return ResourceManager.GetString("memberalreadyexisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string newpass {
            get {
                return ResourceManager.GetString("newpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter group name.
        /// </summary>
        internal static string pleaseentergroupname {
            get {
                return ResourceManager.GetString("pleaseentergroupname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email.
        /// </summary>
        internal static string pleaseenteryouremail {
            get {
                return ResourceManager.GetString("pleaseenteryouremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your information.
        /// </summary>
        internal static string pleaseenteryourinformation {
            get {
                return ResourceManager.GetString("pleaseenteryourinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        internal static string pleaseenteryourpassword {
            get {
                return ResourceManager.GetString("pleaseenteryourpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string resetpass {
            get {
                return ResourceManager.GetString("resetpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password successfully.
        /// </summary>
        internal static string resetpasswordsuccessfully {
            get {
                return ResourceManager.GetString("resetpasswordsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send code.
        /// </summary>
        internal static string sendcode {
            get {
                return ResourceManager.GetString("sendcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your new password.
        /// </summary>
        internal static string setyournewpass {
            get {
                return ResourceManager.GetString("setyournewpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string signout {
            get {
                return ResourceManager.GetString("signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silent mode.
        /// </summary>
        internal static string silentmode {
            get {
                return ResourceManager.GetString("silentmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texting.
        /// </summary>
        internal static string texting {
            get {
                return ResourceManager.GetString("texting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string verify {
            get {
                return ResourceManager.GetString("verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        internal static string vietnamese {
            get {
                return ResourceManager.GetString("vietnamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong email or password.
        /// </summary>
        internal static string wrongemailorpassword {
            get {
                return ResourceManager.GetString("wrongemailorpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong verification code.
        /// </summary>
        internal static string wrongverificationcode {
            get {
                return ResourceManager.GetString("wrongverificationcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email.
        /// </summary>
        internal static string youremail {
            get {
                return ResourceManager.GetString("youremail", resourceCulture);
            }
        }
    }
}
